name: Publish package to GitHub Packages
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish
        run: gradle check publish --no-configure-on-demand --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}